### ISSUE TITLE
Error: spawn node ENOENT in react-scripts / jest-worker

### ISSUE THREAD

**Issue by helloworldless** [node-gradle/gradle-node-plugin#114]
I'm getting the error below from the `yarn_build` task. Based on a bit of research, I'm guessing it doesn't have permissions to spawn a new process.

I did find [this workaround](https://stackoverflow.com/a/58991590). But I thought I'd raise an issue in case there's some fix possible or another suggested workaround, and to help others who may be searching the issues here for a solution.

```text
> Task :ui:yarn_build
yarn run v1.22.5
$ react-scripts build
Creating an optimized production build...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/dgood/IdeaProjects/fullstack-java-react-starter/ui/build/nodejs/node-v12.18.3-linux-x64/bin/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/dgood/IdeaProjects/fullstack-java-react-starter/ui/build/nodejs/node-v12.18.3-linux-x64/bin/node',
  path: '/home/dgood/IdeaProjects/fullstack-java-react-starter/ui/build/nodejs/node-v12.18.3-linux-x64/bin/node',
  spawnargs: [
    '/home/dgood/IdeaProjects/fullstack-java-react-starter/ui/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/processChild.js'
  ]
}
error Command failed with exit code 1.
spawn /home/dgood/IdeaProjects/fullstack-java-react-starter/ui/build/nodejs/node-v12.18.3-linux-x64/bin/node ENOENT
```

Gradle build script excerpt:

```groovy
plugins {
    id "base"
    id "com.github.node-gradle.node" version "2.2.4"

}

node {
    version = '12.18.3'
    npmVersion = '6.14.6'
    yarnVersion = '1.22.5'
    download = true
    workDir = file("${project.buildDir}/nodejs")
    npmWorkDir = file("${project.buildDir}/npm")
    yarnWorkDir = file("${project.buildDir}/yarn")
    nodeModulesDir = file("${project.projectDir}")
}
```

Node Dependency versions:

```json
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-query": "^1.0.26",
    "react-scripts": "3.4.3"
  },
```

**Comment by bsautel** [comment]
I have never been using `react-scripts` but as the workaround is to downgrade it, it sounds like the issue comes from this package? This issue was reported here: facebook/create-react-app#9455. One answer talks about running `react-scripts start` first, another one seems to indicate that something is missing in the `PATH` environment variable.

I'am wondering whether this has anything to do with the Gradle Node plugin. When you run all these commands outside from the plugin, are they working?
