### ISSUE TITLE
Update spock to 2.0 breaks RunWithMultipleGradleVersionsExtension 

### ISSUE THREAD

**Issue by deepy** [node-gradle/gradle-node-plugin#207]
The initial change is easy, replace `extends AbstractAnnotationDrivenExtension` with `implements IAnnotationDrivenExtension`
Add `testImplementation(platform("org.spockframework:spock-bom:2.0-groovy-3.0"))`

and add a `testImplementation("org.spockframework:spock-junit4")` to make `TemporaryDirectory` continue working.

When running with a single version from `RunWithMultipleGradleVersionsExtension` this works fine, but when running with mutliple versions the following happens *after* the tests finish:

```
java.util.NoSuchElementException
	at java.base/java.util.LinkedList.removeFirst(LinkedList.java:274)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:76)
	at com.github.gradle.node.npm.task.NpmInstall_integTest.install packages with npm(NpmInstall_integTest.groovy:39)
	Suppressed: java.util.NoSuchElementException
		... 3 more
```

**Comment by deepy** [comment]
Switched version injection system.
