### ISSUE TITLE
npm-cli

### ISSUE THREAD

**Issue by Jonatha1983** [node-gradle/gradle-node-plugin#56]
Hi 

I am working on converting a mvn project into gradle. 

I see that in mvn at the end it run this command:
```
node/node_modules/npm/bin/npm-cli.js, run, build
```

And I would like to achieve the same. 

I tried different approach with npmTask or npxTask  also tried to do the same as in the @angular/cli example but without success. 

Any suggestions ? 

Thanks ahead

**Comment by deepy** [comment]
Can you paste the NpmTask you tried? I think npm run build might be what you're looking for.
(Untested and written on my phone:)
```groovy
task npmRunBuild(type: NpmTask) {
  args = ['run', 'build']
}
```

**Comment by Jonatha1983** [comment]
Thanks @deepy 

This is exactly what I tried but I keep getting the following error:

```
react-scripts/config/webpack.config.js:310
        ...(isEnvProductionProfile && {
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

this is my task:
```
task npmBuildTask(type: NpmTask) { Task npmTask ->
    npmTask.dependsOn npmInstall
    npmTask.args += ["run", "build"]
    npmTask.environment = ['NODE_ENV': 'production']
    npmTask.inputs.files('package.json', 'package-lock.json')
    npmTask.inputs.dir('src')
    npmTask.inputs.dir(fileTree("node_modules").exclude(".cache"))
    npmTask.outputs.dir("${project.buildDir}/classes/resources")
}
```

**Comment by Jonatha1983** [comment]
When I looking in this file:
```
node_modules/react-scripts/config/webpack.config.js:310
```
I do see the error syntax - but not sure where it is coming from ...

**Comment by Jonatha1983** [comment]
In addition this is my package.json initial:

```
"dependencies": {
    "classnames": "^2.2.6",
    "history": "^4.9.0",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "node-sass": "^4.12.0",
    "prop-types": "^15.7.2",
    "qs": "^6.7.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-redux": "^7.1.1",
    "react-router-dom": "^5.0.1",
    "react-scripts": "^3.3.0",
    "react-sortable-hoc": "1.9.1",
    "redux": "^4.0.1",
    "redux-actions": "^2.6.5",
    "reselect": "^4.0.0",
    "taboola-ultimate-ui": "^1.0.97"
  },
  "scripts": {
    "build": "react-scripts build",
  ...
```

**Comment by bsautel** [comment]
This file did work with Maven and not with Gradle, right?
Do you know which Node.js version is used by Maven and by Gradle?

**Comment by deepy** [comment]
Closing this as there's been no response.
