### ISSUE TITLE
GStringImpl ClassCastException issue in version 3

### ISSUE THREAD

**Issue by henrik242** [node-gradle/gradle-node-plugin#76]
The following works in 2.2.1, but fails in 2.2.2:

```
tasks.withType(YarnTask) { task ->
    task.dependsOn(":someTask")
    addPathToYarnFor(task)
}

def addPathToYarnFor(task) {
    task.configure {
        String yarnPath = "${rootDir}/build/yarn/bin"
        environment = ["PATH": "${yarnPath}:${System.env.PATH}"]
    }
}
```

A workaround is to use `toString()`:         
```
environment = ["PATH": "${yarnPath}:${System.env.PATH}".toString()]
```
Here's the exception:
```
Caused by: java.lang.ClassCastException: class org.codehaus.groovy.runtime.GStringImpl cannot be cast to class java.lang.String (org.codehaus.groovy.runtime.GStringImpl is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @5d6f64b1; java.lang.String is in module java.base of loader 'bootstrap')
        at com.moowork.gradle.node.exec.ExecRunner.computeExecEnvironment(ExecRunner.kt:66)
        at com.moowork.gradle.node.exec.ExecRunner.access$computeExecEnvironment(ExecRunner.kt:16)
        at com.moowork.gradle.node.exec.ExecRunner$run$1.execute(ExecRunner.kt:44)
        at com.moowork.gradle.node.exec.ExecRunner$run$1.execute(ExecRunner.kt:16)
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:151)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1139)
        at com.moowork.gradle.node.exec.ExecRunner.run(ExecRunner.kt:41)
        at com.moowork.gradle.node.yarn.YarnExecRunner.doExecute(YarnExecRunner.kt:11)
        at com.moowork.gradle.node.exec.ExecRunner.execute(ExecRunner.kt:37)
        at com.moowork.gradle.node.yarn.YarnTask.exec(YarnTask.kt:43)
```
Should I just use the `toString()` or do you plan to support `GString`?

**Comment by deepy** [comment]
Hmm, this is tricky, from how I understood GString is that groovy should automatically convert it to a String if necessary, so `toString()` *shouldn't* be necessary, although obviously something is going wrong here.

Go with `toString()` for now while we work on a fix, sorry about the inconvenience

**Comment by henrik242** [comment]
@deepy I've seen this a lot with Groovy. No easy fix, I think, other than replacing `Map<String, String>` with a `Map<String, Any>`  and do a `mapValues { it.toString() }` on it.

**Comment by deepy** [comment]
Aargh, maybe we can add a setter for `Map<String, Any>` and get partial support, I'll have to look into this

**Comment by bsautel** [comment]
This regression is due to an error in the release process. The 2.2.2 release should be a fix-only release and it integrated all the changes applied to the master branch, including the Kotlin rewrite that breaks backward compatibility.

We are going to release a new 2.2.3 version which won't include this issue. But this issue is still valid for the development branch and is probably due to the Kotlin rewrite.

**Comment by bsautel** [comment]
I added some GStrings in the integration tests in bb4941c  to ensure GStrings work as expected and I could not reproduce the issue. Did I forget anything?
